apiVersion: v2
name: users-api
description: A Helm chart for Kubernetes

type: application

version: 0.3.0
appVersion: 0.10.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database
