{
 "title": "My dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"myapp-users-api-.*\"}[5m])) by (pod)",
     "legendFormat": "CPU {{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\"myapp-users-api-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "RPS Ingress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Latency Ingress (50)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n      sum by (le) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency Ingress (95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n      sum by (le) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Error Rate Ingress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency Ingress (99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n      sum by (le) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency Ingress (Max)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99999, \r\n      sum by (le) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "Latency"
    }
   ]
  },
  { "title": "App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(app_request_count[1m]))",
     "legendFormat": "RPS {{path}}"
    }
   ]
  },
  {
   "title": "Latency (50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n      sum by (le, path) \r\n         (rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency (90)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, \r\n      sum by (le, path) \r\n         (rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(app_request_count{http_status=~\"5.*\"}[2m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency (99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n      sum by (le, path) \r\n         (rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99999, \r\n      sum by (le, path) \r\n         (rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}