{
 "title": "My dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(app_request_count[1m]))",
     "legendFormat": "RPS {{path}}"
    }
   ]
  },
  {
   "title": "Latency By Endpoint - 50",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n      sum by (le, path) \r\n         (rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000\r"
    }
   ]
  },
  {
   "title": "Latency By Endpoint - 99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n      sum by (le, path) \r\n         (rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000\r"
    }
   ]
  },
  {
   "title": "Latency By Endpoint - 90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, \r\n      sum by (le, path) \r\n         (rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000\r"
    }
   ]
  }
 ]
}